# Generated by Django 5.2 on 2026-05-26 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Run",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="running", max_length=20)),
                (
                    "budget_usd",
                    models.DecimalField(decimal_places=4, default=5, max_digits=10),
                ),
                (
                    "spent_usd",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=2000)),
                ("url_hash", models.CharField(db_index=True, max_length=40)),
                ("status_code", models.IntegerField(null=True)),
                ("indexable", models.BooleanField(default=True)),
                ("title", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("h1", models.TextField(blank=True)),
                ("h2s", models.JSONField(default=list)),
                ("canonical", models.URLField(blank=True, max_length=2000)),
                ("word_count", models.IntegerField(null=True)),
                ("body", models.TextField(blank=True)),
                ("reasons", models.JSONField(default=list)),
                (
                    "input_hash",
                    models.CharField(blank=True, db_index=True, max_length=40),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="metadata.run",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Draft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=80, unique=True)),
                ("url", models.URLField(max_length=2000)),
                ("title", models.TextField()),
                ("description", models.TextField()),
                ("rationale", models.TextField(blank=True)),
                ("confidence", models.FloatField(null=True)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("input_tokens", models.IntegerField(default=0)),
                ("output_tokens", models.IntegerField(default=0)),
                (
                    "input_hash",
                    models.CharField(blank=True, db_index=True, max_length=40),
                ),
                (
                    "cost_usd",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                ("reviewed_by", models.CharField(blank=True, max_length=150)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drafts",
                        to="metadata.page",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drafts",
                        to="metadata.run",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="page",
            constraint=models.UniqueConstraint(
                fields=("run", "url_hash"), name="page_once_per_run"
            ),
        ),
    ]
